-- Phase 19-36 consolidated migration
-- Phases: 19 (Global Search), 20 (Help/Localization), 21 (Data Governance),
--         22 (OAuth/MFA), 23 (Cohorts/Timezone), 24 (Realtime),
--         25 (Bulk Ops), 26 (Moderation/Legal), 27 (Direct Messaging),
--         28 (Proctoring), 29 (Revenue Share/Payout), 30 (Tax/Multi-currency),
--         31 (3D Content), 32 (Code Runner), 33 (Plugin Marketplace),
--         34 (Popout Dual Monitor), 35 (Transcript Notes), 36 (Plugin Workspace Panels)
-- Generated by consolidating the split migration files in the same directory.

-- =====================================================
-- Source: 20260706061000_phase_19_20_35\migration.sql
-- =====================================================

-- Phase 19: Global Search
-- Phase 20: Localization and Help Center
-- Phase 35: Transcript Notes AI Context

-- SearchQuery
CREATE TABLE "SearchQuery" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "query" TEXT NOT NULL,
  "types" JSONB NOT NULL DEFAULT '[]',
  "resultsCount" INTEGER NOT NULL DEFAULT 0,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SearchQuery_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "SearchQuery_organizationId_createdAt_idx" ON "SearchQuery"("organizationId", "createdAt");
CREATE INDEX "SearchQuery_organizationId_userId_idx" ON "SearchQuery"("organizationId", "userId");
CREATE INDEX "SearchQuery_organizationId_query_idx" ON "SearchQuery"("organizationId", "query");
ALTER TABLE "SearchQuery" ADD CONSTRAINT "SearchQuery_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SearchQuery" ADD CONSTRAINT "SearchQuery_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- HelpCategory
CREATE TABLE "HelpCategory" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "icon" TEXT,
  "orderIndex" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "HelpCategory_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "HelpCategory_organizationId_key_key" ON "HelpCategory"("organizationId", "key");
CREATE INDEX "HelpCategory_organizationId_orderIndex_idx" ON "HelpCategory"("organizationId", "orderIndex");
ALTER TABLE "HelpCategory" ADD CONSTRAINT "HelpCategory_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- HelpArticle
CREATE TABLE "HelpArticle" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "categoryId" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "excerpt" TEXT,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "tags" JSONB NOT NULL DEFAULT '[]',
  "viewCount" INTEGER NOT NULL DEFAULT 0,
  "publishedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "HelpArticle_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "HelpArticle_organizationId_slug_key" ON "HelpArticle"("organizationId", "slug");
CREATE INDEX "HelpArticle_organizationId_categoryId_idx" ON "HelpArticle"("organizationId", "categoryId");
CREATE INDEX "HelpArticle_organizationId_status_idx" ON "HelpArticle"("organizationId", "status");
ALTER TABLE "HelpArticle" ADD CONSTRAINT "HelpArticle_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HelpArticle" ADD CONSTRAINT "HelpArticle_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "HelpCategory"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- HelpArticleView
CREATE TABLE "HelpArticleView" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "articleId" TEXT NOT NULL,
  "userId" TEXT,
  "viewedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "HelpArticleView_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "HelpArticleView_organizationId_articleId_idx" ON "HelpArticleView"("organizationId", "articleId");
CREATE INDEX "HelpArticleView_organizationId_viewedAt_idx" ON "HelpArticleView"("organizationId", "viewedAt");
ALTER TABLE "HelpArticleView" ADD CONSTRAINT "HelpArticleView_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HelpArticleView" ADD CONSTRAINT "HelpArticleView_articleId_fkey" FOREIGN KEY ("articleId") REFERENCES "HelpArticle"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HelpArticleView" ADD CONSTRAINT "HelpArticleView_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- SupportTicket
CREATE TABLE "SupportTicket" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "category" TEXT NOT NULL DEFAULT 'general',
  "priority" TEXT NOT NULL DEFAULT 'NORMAL',
  "status" TEXT NOT NULL DEFAULT 'OPEN',
  "assignedToId" TEXT,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "closedAt" TIMESTAMP(3),
  CONSTRAINT "SupportTicket_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "SupportTicket_organizationId_userId_idx" ON "SupportTicket"("organizationId", "userId");
CREATE INDEX "SupportTicket_organizationId_status_idx" ON "SupportTicket"("organizationId", "status");
CREATE INDEX "SupportTicket_organizationId_createdAt_idx" ON "SupportTicket"("organizationId", "createdAt");
ALTER TABLE "SupportTicket" ADD CONSTRAINT "SupportTicket_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupportTicket" ADD CONSTRAINT "SupportTicket_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupportTicket" ADD CONSTRAINT "SupportTicket_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- SupportTicketReply
CREATE TABLE "SupportTicketReply" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "ticketId" TEXT NOT NULL,
  "authorId" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "isInternal" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SupportTicketReply_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "SupportTicketReply_organizationId_ticketId_idx" ON "SupportTicketReply"("organizationId", "ticketId");
ALTER TABLE "SupportTicketReply" ADD CONSTRAINT "SupportTicketReply_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupportTicketReply" ADD CONSTRAINT "SupportTicketReply_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "SupportTicket"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupportTicketReply" ADD CONSTRAINT "SupportTicketReply_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- UserLocalePreference
CREATE TABLE "UserLocalePreference" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "locale" TEXT NOT NULL DEFAULT 'en',
  "timezone" TEXT NOT NULL DEFAULT 'UTC',
  "fallbackChain" JSONB NOT NULL DEFAULT '[]',
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "UserLocalePreference_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "UserLocalePreference_organizationId_userId_key" ON "UserLocalePreference"("organizationId", "userId");
ALTER TABLE "UserLocalePreference" ADD CONSTRAINT "UserLocalePreference_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserLocalePreference" ADD CONSTRAINT "UserLocalePreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- OrgLocalePreference
CREATE TABLE "OrgLocalePreference" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "defaultLocale" TEXT NOT NULL DEFAULT 'en',
  "supportedLocales" JSONB NOT NULL DEFAULT '["en"]',
  "fallbackChain" JSONB NOT NULL DEFAULT '["en"]',
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "OrgLocalePreference_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "OrgLocalePreference_organizationId_key" ON "OrgLocalePreference"("organizationId");
ALTER TABLE "OrgLocalePreference" ADD CONSTRAINT "OrgLocalePreference_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- TranscriptNote
CREATE TABLE "TranscriptNote" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "lessonId" TEXT NOT NULL,
  "activityId" TEXT,
  "timestampSeconds" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "content" TEXT NOT NULL,
  "color" TEXT NOT NULL DEFAULT 'yellow',
  "tags" JSONB NOT NULL DEFAULT '[]',
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TranscriptNote_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "TranscriptNote_organizationId_userId_idx" ON "TranscriptNote"("organizationId", "userId");
CREATE INDEX "TranscriptNote_organizationId_lessonId_idx" ON "TranscriptNote"("organizationId", "lessonId");
CREATE INDEX "TranscriptNote_organizationId_activityId_idx" ON "TranscriptNote"("organizationId", "activityId");
ALTER TABLE "TranscriptNote" ADD CONSTRAINT "TranscriptNote_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TranscriptNote" ADD CONSTRAINT "TranscriptNote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TranscriptNote" ADD CONSTRAINT "TranscriptNote_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TranscriptNote" ADD CONSTRAINT "TranscriptNote_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- NoteContext
CREATE TABLE "NoteContext" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "noteId" TEXT NOT NULL,
  "aiContextSummary" TEXT NOT NULL,
  "relatedNotes" JSONB NOT NULL DEFAULT '[]',
  "providerKey" TEXT NOT NULL DEFAULT 'mock',
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "NoteContext_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "NoteContext_noteId_key" ON "NoteContext"("noteId");
CREATE INDEX "NoteContext_organizationId_createdAt_idx" ON "NoteContext"("organizationId", "createdAt");
ALTER TABLE "NoteContext" ADD CONSTRAINT "NoteContext_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NoteContext" ADD CONSTRAINT "NoteContext_noteId_fkey" FOREIGN KEY ("noteId") REFERENCES "TranscriptNote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- NotesExport
CREATE TABLE "NotesExport" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "lessonId" TEXT,
  "format" TEXT NOT NULL DEFAULT 'markdown',
  "status" TEXT NOT NULL DEFAULT 'COMPLETED',
  "markdown" TEXT NOT NULL DEFAULT '',
  "count" INTEGER NOT NULL DEFAULT 0,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NotesExport_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "NotesExport_organizationId_userId_idx" ON "NotesExport"("organizationId", "userId");
CREATE INDEX "NotesExport_organizationId_lessonId_idx" ON "NotesExport"("organizationId", "lessonId");
ALTER TABLE "NotesExport" ADD CONSTRAINT "NotesExport_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotesExport" ADD CONSTRAINT "NotesExport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotesExport" ADD CONSTRAINT "NotesExport_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- =====================================================
-- Source: 20260706070000_phase_21_22_26\migration.sql
-- =====================================================

-- Phase 21: Data Governance & Backup
-- Phase 22: OAuth, Captcha, MFA
-- Phase 26: Moderation, Legal, Consent

-- ===========================================================================
-- Enums (Phase 21)
-- ===========================================================================

CREATE TYPE "LegalDocumentType" AS ENUM (
  'PRIVACY_POLICY',
  'TERMS',
  'COOKIE_POLICY',
  'DPA'
);

CREATE TYPE "BackupJobType" AS ENUM (
  'FULL',
  'INCREMENTAL'
);

CREATE TYPE "BackupJobStatus" AS ENUM (
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'FAILED'
);

-- ===========================================================================
-- Enums (Phase 22)
-- ===========================================================================

CREATE TYPE "OAuthProvider" AS ENUM (
  'GOOGLE',
  'MICROSOFT'
);

CREATE TYPE "MfaFactorType" AS ENUM (
  'TOTP',
  'BACKUP_CODE'
);

-- ===========================================================================
-- Enums (Phase 26)
-- ===========================================================================

CREATE TYPE "ModerationTargetType" AS ENUM (
  'CONTENT',
  'USER',
  'COMMENT',
  'COURSE',
  'DISCUSSION'
);

CREATE TYPE "ModerationReportStatus" AS ENUM (
  'OPEN',
  'IN_REVIEW',
  'RESOLVED',
  'DISMISSED'
);

CREATE TYPE "ModerationActionType" AS ENUM (
  'WARN',
  'SUSPEND',
  'BAN',
  'REMOVE',
  'RESTORE',
  'LOCK'
);

-- ===========================================================================
-- Phase 21: Legal Document
-- ===========================================================================

CREATE TABLE "LegalDocument" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "type" "LegalDocumentType" NOT NULL,
  "version" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "effectiveAt" TIMESTAMP(3) NOT NULL,
  "publishedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "LegalDocument_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "LegalDocument_organizationId_type_version_key"
  ON "LegalDocument"("organizationId", "type", "version");
CREATE INDEX "LegalDocument_organizationId_type_idx"
  ON "LegalDocument"("organizationId", "type");

ALTER TABLE "LegalDocument"
  ADD CONSTRAINT "LegalDocument_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 21: Consent Record
-- ===========================================================================

CREATE TABLE "ConsentRecord" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "documentId" TEXT,
  "documentType" "LegalDocumentType" NOT NULL,
  "documentVersion" TEXT NOT NULL,
  "granted" BOOLEAN NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ConsentRecord_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ConsentRecord_organizationId_userId_idx"
  ON "ConsentRecord"("organizationId", "userId");
CREATE INDEX "ConsentRecord_organizationId_documentType_idx"
  ON "ConsentRecord"("organizationId", "documentType");

ALTER TABLE "ConsentRecord"
  ADD CONSTRAINT "ConsentRecord_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 21: Data Export Request
-- ===========================================================================

CREATE TABLE "DataExportRequest" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMP(3),
  "downloadUrl" TEXT,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  CONSTRAINT "DataExportRequest_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "DataExportRequest_organizationId_userId_idx"
  ON "DataExportRequest"("organizationId", "userId");
CREATE INDEX "DataExportRequest_organizationId_status_idx"
  ON "DataExportRequest"("organizationId", "status");

ALTER TABLE "DataExportRequest"
  ADD CONSTRAINT "DataExportRequest_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 21: Anonymization Request
-- ===========================================================================

CREATE TABLE "AnonymizationRequest" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMP(3),
  "reason" TEXT,
  CONSTRAINT "AnonymizationRequest_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "AnonymizationRequest_organizationId_userId_idx"
  ON "AnonymizationRequest"("organizationId", "userId");
CREATE INDEX "AnonymizationRequest_organizationId_status_idx"
  ON "AnonymizationRequest"("organizationId", "status");

ALTER TABLE "AnonymizationRequest"
  ADD CONSTRAINT "AnonymizationRequest_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 21: Retention Policy
-- ===========================================================================

CREATE TABLE "RetentionPolicy" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "entityType" TEXT NOT NULL,
  "retentionDays" INTEGER NOT NULL DEFAULT 365,
  "anonymize" BOOLEAN NOT NULL DEFAULT true,
  "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "RetentionPolicy_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "RetentionPolicy_organizationId_entityType_key"
  ON "RetentionPolicy"("organizationId", "entityType");
CREATE INDEX "RetentionPolicy_organizationId_idx"
  ON "RetentionPolicy"("organizationId");

ALTER TABLE "RetentionPolicy"
  ADD CONSTRAINT "RetentionPolicy_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 21: Backup Job
-- ===========================================================================

CREATE TABLE "BackupJob" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "type" "BackupJobType" NOT NULL,
  "status" "BackupJobStatus" NOT NULL DEFAULT 'PENDING',
  "startedAt" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "sizeBytes" BIGINT,
  "location" TEXT,
  "notes" TEXT,
  "triggeredBy" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BackupJob_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "BackupJob_organizationId_status_idx"
  ON "BackupJob"("organizationId", "status");
CREATE INDEX "BackupJob_organizationId_createdAt_idx"
  ON "BackupJob"("organizationId", "createdAt");

ALTER TABLE "BackupJob"
  ADD CONSTRAINT "BackupJob_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 21: Cookie Consent
-- ===========================================================================

CREATE TABLE "CookieConsent" (
  "id" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "necessary" BOOLEAN NOT NULL DEFAULT true,
  "analytics" BOOLEAN NOT NULL DEFAULT false,
  "marketing" BOOLEAN NOT NULL DEFAULT false,
  "preferences" BOOLEAN NOT NULL DEFAULT false,
  "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  CONSTRAINT "CookieConsent_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "CookieConsent_organizationId_sessionId_key"
  ON "CookieConsent"("organizationId", "sessionId");
CREATE INDEX "CookieConsent_organizationId_grantedAt_idx"
  ON "CookieConsent"("organizationId", "grantedAt");

ALTER TABLE "CookieConsent"
  ADD CONSTRAINT "CookieConsent_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 22: OAuth Account
-- ===========================================================================

CREATE TABLE "OAuthAccount" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "organizationId" TEXT,
  "provider" "OAuthProvider" NOT NULL,
  "providerUserId" TEXT NOT NULL,
  "email" TEXT,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "expiresAt" TIMESTAMP(3),
  "rawProfile" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "OAuthAccount_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "OAuthAccount_provider_providerUserId_key"
  ON "OAuthAccount"("provider", "providerUserId");
CREATE INDEX "OAuthAccount_userId_idx"
  ON "OAuthAccount"("userId");

ALTER TABLE "OAuthAccount"
  ADD CONSTRAINT "OAuthAccount_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 22: MFA Factor
-- ===========================================================================

CREATE TABLE "MfaFactor" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "organizationId" TEXT,
  "type" "MfaFactorType" NOT NULL,
  "secret" TEXT,
  "backupCodes" JSONB NOT NULL DEFAULT '[]',
  "verifiedAt" TIMESTAMP(3),
  "lastUsedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "MfaFactor_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "MfaFactor_userId_type_idx" ON "MfaFactor"("userId", "type");
CREATE INDEX "MfaFactor_userId_verifiedAt_idx" ON "MfaFactor"("userId", "verifiedAt");

ALTER TABLE "MfaFactor"
  ADD CONSTRAINT "MfaFactor_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 22: Refresh Session (extended session tracking)
-- ===========================================================================

CREATE TABLE "RefreshSession" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "refreshTokenHash" TEXT NOT NULL,
  "deviceInfo" TEXT,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "lastUsedAt" TIMESTAMP(3),
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "revokedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "RefreshSession_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "RefreshSession_refreshTokenHash_key"
  ON "RefreshSession"("refreshTokenHash");
CREATE INDEX "RefreshSession_userId_idx" ON "RefreshSession"("userId");
CREATE INDEX "RefreshSession_expiresAt_idx" ON "RefreshSession"("expiresAt");
CREATE INDEX "RefreshSession_userId_revokedAt_idx"
  ON "RefreshSession"("userId", "revokedAt");

ALTER TABLE "RefreshSession"
  ADD CONSTRAINT "RefreshSession_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 22: Login Attempt
-- ===========================================================================

CREATE TABLE "LoginAttempt" (
  "id" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "organizationId" TEXT,
  "userId" TEXT,
  "success" BOOLEAN NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "captchaToken" TEXT,
  "reason" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "LoginAttempt_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "LoginAttempt_email_createdAt_idx"
  ON "LoginAttempt"("email", "createdAt");
CREATE INDEX "LoginAttempt_organizationId_createdAt_idx"
  ON "LoginAttempt"("organizationId", "createdAt");
CREATE INDEX "LoginAttempt_ipAddress_createdAt_idx"
  ON "LoginAttempt"("ipAddress", "createdAt");

ALTER TABLE "LoginAttempt"
  ADD CONSTRAINT "LoginAttempt_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 26: Moderation Report
-- ===========================================================================

CREATE TABLE "ModerationReport" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "reporterId" TEXT NOT NULL,
  "targetType" "ModerationTargetType" NOT NULL,
  "targetId" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "description" TEXT,
  "status" "ModerationReportStatus" NOT NULL DEFAULT 'OPEN',
  "reviewedById" TEXT,
  "reviewedAt" TIMESTAMP(3),
  "resolution" TEXT,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ModerationReport_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ModerationReport_organizationId_status_idx"
  ON "ModerationReport"("organizationId", "status");
CREATE INDEX "ModerationReport_organizationId_targetType_targetId_idx"
  ON "ModerationReport"("organizationId", "targetType", "targetId");
CREATE INDEX "ModerationReport_organizationId_createdAt_idx"
  ON "ModerationReport"("organizationId", "createdAt");

ALTER TABLE "ModerationReport"
  ADD CONSTRAINT "ModerationReport_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ModerationReport"
  ADD CONSTRAINT "ModerationReport_reporterId_fkey"
  FOREIGN KEY ("reporterId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ModerationReport"
  ADD CONSTRAINT "ModerationReport_reviewedById_fkey"
  FOREIGN KEY ("reviewedById") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 26: Moderation Action
-- ===========================================================================

CREATE TABLE "ModerationAction" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "actorId" TEXT NOT NULL,
  "targetType" "ModerationTargetType" NOT NULL,
  "targetId" TEXT NOT NULL,
  "actionType" "ModerationActionType" NOT NULL,
  "reason" TEXT NOT NULL,
  "notes" TEXT,
  "expiresAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ModerationAction_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ModerationAction_organizationId_targetType_targetId_idx"
  ON "ModerationAction"("organizationId", "targetType", "targetId");
CREATE INDEX "ModerationAction_organizationId_actionType_idx"
  ON "ModerationAction"("organizationId", "actionType");
CREATE INDEX "ModerationAction_organizationId_createdAt_idx"
  ON "ModerationAction"("organizationId", "createdAt");

ALTER TABLE "ModerationAction"
  ADD CONSTRAINT "ModerationAction_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ModerationAction"
  ADD CONSTRAINT "ModerationAction_actorId_fkey"
  FOREIGN KEY ("actorId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 26: Content Flag
-- ===========================================================================

CREATE TABLE "ContentFlag" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "flaggedById" TEXT,
  "targetType" "ModerationTargetType" NOT NULL,
  "targetId" TEXT NOT NULL,
  "flagType" TEXT NOT NULL,
  "autoDetected" BOOLEAN NOT NULL DEFAULT false,
  "confidence" DOUBLE PRECISION,
  "reason" TEXT,
  "resolvedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ContentFlag_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ContentFlag_organizationId_targetType_targetId_idx"
  ON "ContentFlag"("organizationId", "targetType", "targetId");
CREATE INDEX "ContentFlag_organizationId_flagType_idx"
  ON "ContentFlag"("organizationId", "flagType");
CREATE INDEX "ContentFlag_organizationId_autoDetected_idx"
  ON "ContentFlag"("organizationId", "autoDetected");

ALTER TABLE "ContentFlag"
  ADD CONSTRAINT "ContentFlag_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ContentFlag"
  ADD CONSTRAINT "ContentFlag_flaggedById_fkey"
  FOREIGN KEY ("flaggedById") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 26: Legal Acceptance Log
-- ===========================================================================

CREATE TABLE "LegalAcceptanceLog" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "documentType" "LegalDocumentType" NOT NULL,
  "documentVersion" TEXT NOT NULL,
  "acceptedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  CONSTRAINT "LegalAcceptanceLog_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "LegalAcceptanceLog_organizationId_userId_idx"
  ON "LegalAcceptanceLog"("organizationId", "userId");
CREATE INDEX "LegalAcceptanceLog_organizationId_documentType_idx"
  ON "LegalAcceptanceLog"("organizationId", "documentType");

ALTER TABLE "LegalAcceptanceLog"
  ADD CONSTRAINT "LegalAcceptanceLog_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================
-- Source: 20260706090100_phase_23_28_29_30\migration.sql
-- =====================================================

-- Phase 23: Timezone & cohort scheduling
-- Phase 28: Proctoring
-- Phase 29: Revenue share & payout
-- Phase 30: Multi-currency & tax

-- =====================================================================
-- Phase 23: Timezone & cohort scheduling
-- =====================================================================

CREATE TYPE "CohortStatus" AS ENUM ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE "CohortMemberStatus" AS ENUM ('ACTIVE', 'WITHDRAWN', 'COMPLETED');

CREATE TABLE "Cohort" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "courseId" TEXT NOT NULL,
  "startAt" TIMESTAMP(3) NOT NULL,
  "endAt" TIMESTAMP(3) NOT NULL,
  "timezone" TEXT NOT NULL DEFAULT 'UTC',
  "maxSeats" INTEGER NOT NULL DEFAULT 0,
  "status" "CohortStatus" NOT NULL DEFAULT 'PLANNED',
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Cohort_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Cohort_organizationId_courseId_idx" ON "Cohort"("organizationId", "courseId");
CREATE INDEX "Cohort_organizationId_status_idx" ON "Cohort"("organizationId", "status");
CREATE INDEX "Cohort_organizationId_startAt_idx" ON "Cohort"("organizationId", "startAt");
ALTER TABLE "Cohort"
  ADD CONSTRAINT "Cohort_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Cohort"
  ADD CONSTRAINT "Cohort_courseId_fkey"
  FOREIGN KEY ("courseId") REFERENCES "Course"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "CohortMember" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "cohortId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "status" "CohortMemberStatus" NOT NULL DEFAULT 'ACTIVE',
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CohortMember_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "CohortMember_cohortId_userId_key" ON "CohortMember"("cohortId", "userId");
CREATE INDEX "CohortMember_organizationId_userId_idx" ON "CohortMember"("organizationId", "userId");
CREATE INDEX "CohortMember_organizationId_status_idx" ON "CohortMember"("organizationId", "status");
ALTER TABLE "CohortMember"
  ADD CONSTRAINT "CohortMember_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CohortMember"
  ADD CONSTRAINT "CohortMember_cohortId_fkey"
  FOREIGN KEY ("cohortId") REFERENCES "Cohort"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CohortMember"
  ADD CONSTRAINT "CohortMember_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "CohortSchedule" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "cohortId" TEXT NOT NULL,
  "weekday" INTEGER NOT NULL,
  "startTime" TEXT NOT NULL,
  "endTime" TEXT NOT NULL,
  "lessonId" TEXT,
  "meetingUrl" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "CohortSchedule_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "CohortSchedule_organizationId_cohortId_idx" ON "CohortSchedule"("organizationId", "cohortId");
CREATE INDEX "CohortSchedule_organizationId_weekday_idx" ON "CohortSchedule"("organizationId", "weekday");
ALTER TABLE "CohortSchedule"
  ADD CONSTRAINT "CohortSchedule_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CohortSchedule"
  ADD CONSTRAINT "CohortSchedule_cohortId_fkey"
  FOREIGN KEY ("cohortId") REFERENCES "Cohort"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CohortSchedule"
  ADD CONSTRAINT "CohortSchedule_lessonId_fkey"
  FOREIGN KEY ("lessonId") REFERENCES "Lesson"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "UserTimezonePreference" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "timezone" TEXT NOT NULL DEFAULT 'UTC',
  "autoDetect" BOOLEAN NOT NULL DEFAULT false,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UserTimezonePreference_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "UserTimezonePreference_userId_key" ON "UserTimezonePreference"("userId");
ALTER TABLE "UserTimezonePreference"
  ADD CONSTRAINT "UserTimezonePreference_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================================
-- Phase 28: Proctoring
-- =====================================================================

CREATE TYPE "ProctoringSessionStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'FLAGGED', 'REVIEWED');
CREATE TYPE "ProctoringEventType" AS ENUM (
  'TAB_SWITCH', 'FULLSCREEN_EXIT', 'COPY_PASTE', 'LOOKING_AWAY',
  'NO_FACE', 'MULTIPLE_FACES', 'PHONE_DETECTED', 'NOISE_DETECTED'
);
CREATE TYPE "ProctoringSeverity" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE "ProctoringFlagStatus" AS ENUM ('OPEN', 'DISMISSED', 'UPHELD');

CREATE TABLE "ProctoringSession" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "attemptId" TEXT NOT NULL,
  "attemptType" TEXT NOT NULL DEFAULT 'quiz',
  "userId" TEXT NOT NULL,
  "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "endedAt" TIMESTAMP(3),
  "status" "ProctoringSessionStatus" NOT NULL DEFAULT 'ACTIVE',
  "integrityScore" DOUBLE PRECISION,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ProctoringSession_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "ProctoringSession_organizationId_attemptId_attemptType_key"
  ON "ProctoringSession"("organizationId", "attemptId", "attemptType");
CREATE INDEX "ProctoringSession_organizationId_userId_idx" ON "ProctoringSession"("organizationId", "userId");
CREATE INDEX "ProctoringSession_organizationId_status_idx" ON "ProctoringSession"("organizationId", "status");
ALTER TABLE "ProctoringSession"
  ADD CONSTRAINT "ProctoringSession_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProctoringSession"
  ADD CONSTRAINT "ProctoringSession_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ProctoringEvent" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "type" "ProctoringEventType" NOT NULL,
  "severity" "ProctoringSeverity" NOT NULL DEFAULT 'LOW',
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProctoringEvent_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ProctoringEvent_organizationId_sessionId_idx" ON "ProctoringEvent"("organizationId", "sessionId");
CREATE INDEX "ProctoringEvent_organizationId_type_idx" ON "ProctoringEvent"("organizationId", "type");
ALTER TABLE "ProctoringEvent"
  ADD CONSTRAINT "ProctoringEvent_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProctoringEvent"
  ADD CONSTRAINT "ProctoringEvent_sessionId_fkey"
  FOREIGN KEY ("sessionId") REFERENCES "ProctoringSession"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ProctoringFlag" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "eventId" TEXT,
  "status" "ProctoringFlagStatus" NOT NULL DEFAULT 'OPEN',
  "notes" TEXT,
  "reviewedBy" TEXT,
  "reviewedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ProctoringFlag_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ProctoringFlag_organizationId_status_idx" ON "ProctoringFlag"("organizationId", "status");
CREATE INDEX "ProctoringFlag_organizationId_sessionId_idx" ON "ProctoringFlag"("organizationId", "sessionId");
ALTER TABLE "ProctoringFlag"
  ADD CONSTRAINT "ProctoringFlag_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProctoringFlag"
  ADD CONSTRAINT "ProctoringFlag_sessionId_fkey"
  FOREIGN KEY ("sessionId") REFERENCES "ProctoringSession"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProctoringFlag"
  ADD CONSTRAINT "ProctoringFlag_eventId_fkey"
  FOREIGN KEY ("eventId") REFERENCES "ProctoringEvent"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProctoringFlag"
  ADD CONSTRAINT "ProctoringFlag_reviewedBy_fkey"
  FOREIGN KEY ("reviewedBy") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- =====================================================================
-- Phase 29: Revenue share & payout
-- =====================================================================

CREATE TYPE "RevenueShareScope" AS ENUM ('PLATFORM', 'INSTRUCTOR', 'COURSE');
CREATE TYPE "PayoutPeriodStatus" AS ENUM ('OPEN', 'LOCKED', 'PAID');
CREATE TYPE "PayoutBeneficiaryType" AS ENUM ('INSTRUCTOR', 'ORG', 'PLATFORM');
CREATE TYPE "PayoutStatus" AS ENUM ('PENDING', 'APPROVED', 'PAID', 'FAILED');
CREATE TYPE "PayoutMethodType" AS ENUM ('BANK', 'PAYPAL', 'STRIPE');

CREATE TABLE "RevenueShareRule" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "scope" "RevenueShareScope" NOT NULL DEFAULT 'INSTRUCTOR',
  "targetId" TEXT,
  "percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "RevenueShareRule_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "RevenueShareRule_organizationId_scope_active_idx"
  ON "RevenueShareRule"("organizationId", "scope", "active");
ALTER TABLE "RevenueShareRule"
  ADD CONSTRAINT "RevenueShareRule_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "PayoutPeriod" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "periodStart" TIMESTAMP(3) NOT NULL,
  "periodEnd" TIMESTAMP(3) NOT NULL,
  "status" "PayoutPeriodStatus" NOT NULL DEFAULT 'OPEN',
  "totalAmount" INTEGER NOT NULL DEFAULT 0,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "lockedAt" TIMESTAMP(3),
  "paidAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PayoutPeriod_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "PayoutPeriod_organizationId_status_idx" ON "PayoutPeriod"("organizationId", "status");
CREATE INDEX "PayoutPeriod_organizationId_periodStart_periodEnd_idx"
  ON "PayoutPeriod"("organizationId", "periodStart", "periodEnd");
ALTER TABLE "PayoutPeriod"
  ADD CONSTRAINT "PayoutPeriod_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "Payout" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "periodId" TEXT NOT NULL,
  "beneficiaryType" "PayoutBeneficiaryType" NOT NULL,
  "beneficiaryId" TEXT NOT NULL,
  "grossAmount" INTEGER NOT NULL DEFAULT 0,
  "feeAmount" INTEGER NOT NULL DEFAULT 0,
  "netAmount" INTEGER NOT NULL DEFAULT 0,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "status" "PayoutStatus" NOT NULL DEFAULT 'PENDING',
  "reference" TEXT,
  "paidAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Payout_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Payout_organizationId_periodId_idx" ON "Payout"("organizationId", "periodId");
CREATE INDEX "Payout_organizationId_status_idx" ON "Payout"("organizationId", "status");
CREATE INDEX "Payout_organizationId_beneficiaryType_beneficiaryId_idx"
  ON "Payout"("organizationId", "beneficiaryType", "beneficiaryId");
ALTER TABLE "Payout"
  ADD CONSTRAINT "Payout_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payout"
  ADD CONSTRAINT "Payout_periodId_fkey"
  FOREIGN KEY ("periodId") REFERENCES "PayoutPeriod"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "PayoutMethod" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "beneficiaryType" "PayoutBeneficiaryType" NOT NULL,
  "beneficiaryId" TEXT NOT NULL,
  "type" "PayoutMethodType" NOT NULL,
  "details" JSONB NOT NULL DEFAULT '{}',
  "verifiedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PayoutMethod_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "PayoutMethod_organizationId_beneficiaryType_beneficiaryId_idx"
  ON "PayoutMethod"("organizationId", "beneficiaryType", "beneficiaryId");
ALTER TABLE "PayoutMethod"
  ADD CONSTRAINT "PayoutMethod_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================================
-- Phase 30: Multi-currency & tax
-- =====================================================================

CREATE TYPE "TaxRuleType" AS ENUM ('VAT', 'GST', 'SALES_TAX');

CREATE TABLE "TaxRegion" (
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "currency" TEXT NOT NULL,
  "taxPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TaxRegion_pkey" PRIMARY KEY ("code")
);

CREATE TABLE "TaxRule" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "regionCode" TEXT NOT NULL,
  "rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "type" "TaxRuleType" NOT NULL DEFAULT 'VAT',
  "inclusive" BOOLEAN NOT NULL DEFAULT false,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TaxRule_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "TaxRule_organizationId_regionCode_active_idx"
  ON "TaxRule"("organizationId", "regionCode", "active");
ALTER TABLE "TaxRule"
  ADD CONSTRAINT "TaxRule_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaxRule"
  ADD CONSTRAINT "TaxRule_regionCode_fkey"
  FOREIGN KEY ("regionCode") REFERENCES "TaxRegion"("code")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "TaxCalculation" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "orderId" TEXT NOT NULL,
  "regionCode" TEXT NOT NULL,
  "subtotal" INTEGER NOT NULL DEFAULT 0,
  "taxAmount" INTEGER NOT NULL DEFAULT 0,
  "total" INTEGER NOT NULL DEFAULT 0,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "breakdown" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TaxCalculation_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "TaxCalculation_organizationId_orderId_idx" ON "TaxCalculation"("organizationId", "orderId");
CREATE INDEX "TaxCalculation_organizationId_regionCode_idx" ON "TaxCalculation"("organizationId", "regionCode");
ALTER TABLE "TaxCalculation"
  ADD CONSTRAINT "TaxCalculation_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaxCalculation"
  ADD CONSTRAINT "TaxCalculation_orderId_fkey"
  FOREIGN KEY ("orderId") REFERENCES "Order"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================
-- Source: 20260706080000_phase_24_25_27\migration.sql
-- =====================================================

-- Phase 24/25/27: Realtime Gateway, Bulk Operations, Direct Messaging

-- ===========================================================================
-- Phase 24: Realtime Gateway
-- ===========================================================================

CREATE TABLE "RealtimeEvent" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "payload" JSONB NOT NULL DEFAULT '{}',
  "actorId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RealtimeEvent_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "RealtimeEvent_organizationId_channel_createdAt_idx"
  ON "RealtimeEvent"("organizationId", "channel", "createdAt");
CREATE INDEX "RealtimeEvent_organizationId_createdAt_idx"
  ON "RealtimeEvent"("organizationId", "createdAt");
ALTER TABLE "RealtimeEvent"
  ADD CONSTRAINT "RealtimeEvent_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RealtimeEvent"
  ADD CONSTRAINT "RealtimeEvent_actorId_fkey"
  FOREIGN KEY ("actorId") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "RealtimeSubscription" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "RealtimeSubscription_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "RealtimeSubscription_userId_channel_key"
  ON "RealtimeSubscription"("userId", "channel");
CREATE INDEX "RealtimeSubscription_organizationId_channel_idx"
  ON "RealtimeSubscription"("organizationId", "channel");
ALTER TABLE "RealtimeSubscription"
  ADD CONSTRAINT "RealtimeSubscription_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RealtimeSubscription"
  ADD CONSTRAINT "RealtimeSubscription_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 25: Bulk Operations
-- ===========================================================================

CREATE TYPE "BulkJobType" AS ENUM (
  'IMPORT',
  'EXPORT',
  'ARCHIVE',
  'UNARCHIVE',
  'ENROLL',
  'UNENROLL',
  'TAG',
  'UNTAG'
);

CREATE TYPE "BulkJobStatus" AS ENUM (
  'PENDING',
  'RUNNING',
  'COMPLETED',
  'FAILED',
  'CANCELLED',
  'PARTIAL'
);

CREATE TYPE "BulkJobItemStatus" AS ENUM (
  'PENDING',
  'PROCESSED',
  'FAILED',
  'SKIPPED'
);

CREATE TABLE "BulkJob" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "type" "BulkJobType" NOT NULL,
  "status" "BulkJobStatus" NOT NULL DEFAULT 'PENDING',
  "input" JSONB NOT NULL DEFAULT '{}',
  "result" JSONB NOT NULL DEFAULT '{}',
  "progressTotal" INTEGER NOT NULL DEFAULT 0,
  "progressDone" INTEGER NOT NULL DEFAULT 0,
  "progressFailed" INTEGER NOT NULL DEFAULT 0,
  "errorMessage" TEXT,
  "startedAt" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "createdById" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BulkJob_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "BulkJob_organizationId_status_idx"
  ON "BulkJob"("organizationId", "status");
CREATE INDEX "BulkJob_organizationId_type_idx"
  ON "BulkJob"("organizationId", "type");
CREATE INDEX "BulkJob_organizationId_createdAt_idx"
  ON "BulkJob"("organizationId", "createdAt");
ALTER TABLE "BulkJob"
  ADD CONSTRAINT "BulkJob_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BulkJob"
  ADD CONSTRAINT "BulkJob_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "BulkJobItem" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "jobId" TEXT NOT NULL,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT,
  "status" "BulkJobItemStatus" NOT NULL DEFAULT 'PENDING',
  "error" TEXT,
  "input" JSONB NOT NULL DEFAULT '{}',
  "processedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "BulkJobItem_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "BulkJobItem_jobId_idx" ON "BulkJobItem"("jobId");
CREATE INDEX "BulkJobItem_organizationId_status_idx"
  ON "BulkJobItem"("organizationId", "status");
ALTER TABLE "BulkJobItem"
  ADD CONSTRAINT "BulkJobItem_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BulkJobItem"
  ADD CONSTRAINT "BulkJobItem_jobId_fkey"
  FOREIGN KEY ("jobId") REFERENCES "BulkJob"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ===========================================================================
-- Phase 27: Direct Messaging
-- ===========================================================================

CREATE TYPE "ConversationType" AS ENUM ('DIRECT', 'GROUP');

CREATE TYPE "ConversationMemberRole" AS ENUM ('MEMBER', 'ADMIN');

CREATE TABLE "Conversation" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "type" "ConversationType" NOT NULL DEFAULT 'DIRECT',
  "createdById" TEXT NOT NULL,
  "name" TEXT,
  "metadata" JSONB NOT NULL DEFAULT '{}',
  "lastMessageAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Conversation_organizationId_lastMessageAt_idx"
  ON "Conversation"("organizationId", "lastMessageAt");
CREATE INDEX "Conversation_organizationId_type_idx"
  ON "Conversation"("organizationId", "type");
ALTER TABLE "Conversation"
  ADD CONSTRAINT "Conversation_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation"
  ADD CONSTRAINT "Conversation_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ConversationMember" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "conversationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "role" "ConversationMemberRole" NOT NULL DEFAULT 'MEMBER',
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastReadAt" TIMESTAMP(3),
  CONSTRAINT "ConversationMember_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "ConversationMember_conversationId_userId_key"
  ON "ConversationMember"("conversationId", "userId");
CREATE INDEX "ConversationMember_organizationId_userId_idx"
  ON "ConversationMember"("organizationId", "userId");
ALTER TABLE "ConversationMember"
  ADD CONSTRAINT "ConversationMember_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConversationMember"
  ADD CONSTRAINT "ConversationMember_conversationId_fkey"
  FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConversationMember"
  ADD CONSTRAINT "ConversationMember_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "Message" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "conversationId" TEXT NOT NULL,
  "senderId" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "attachments" JSONB NOT NULL DEFAULT '[]',
  "parentMessageId" TEXT,
  "editedAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Message_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Message_organizationId_conversationId_createdAt_idx"
  ON "Message"("organizationId", "conversationId", "createdAt");
CREATE INDEX "Message_organizationId_senderId_idx"
  ON "Message"("organizationId", "senderId");
CREATE INDEX "Message_parentMessageId_idx"
  ON "Message"("parentMessageId");
ALTER TABLE "Message"
  ADD CONSTRAINT "Message_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message"
  ADD CONSTRAINT "Message_conversationId_fkey"
  FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message"
  ADD CONSTRAINT "Message_senderId_fkey"
  FOREIGN KEY ("senderId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message"
  ADD CONSTRAINT "Message_parentMessageId_fkey"
  FOREIGN KEY ("parentMessageId") REFERENCES "Message"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "MessageReaction" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "messageId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "emoji" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "MessageReaction_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "MessageReaction_messageId_userId_emoji_key"
  ON "MessageReaction"("messageId", "userId", "emoji");
CREATE INDEX "MessageReaction_organizationId_messageId_idx"
  ON "MessageReaction"("organizationId", "messageId");
ALTER TABLE "MessageReaction"
  ADD CONSTRAINT "MessageReaction_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MessageReaction"
  ADD CONSTRAINT "MessageReaction_messageId_fkey"
  FOREIGN KEY ("messageId") REFERENCES "Message"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MessageReaction"
  ADD CONSTRAINT "MessageReaction_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "MessageRead" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "messageId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "readAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "MessageRead_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "MessageRead_messageId_userId_key"
  ON "MessageRead"("messageId", "userId");
CREATE INDEX "MessageRead_organizationId_userId_idx"
  ON "MessageRead"("organizationId", "userId");
ALTER TABLE "MessageRead"
  ADD CONSTRAINT "MessageRead_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MessageRead"
  ADD CONSTRAINT "MessageRead_messageId_fkey"
  FOREIGN KEY ("messageId") REFERENCES "Message"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MessageRead"
  ADD CONSTRAINT "MessageRead_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "UserBlock" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "blockerId" TEXT NOT NULL,
  "blockedId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UserBlock_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "UserBlock_blockerId_blockedId_key"
  ON "UserBlock"("blockerId", "blockedId");
CREATE INDEX "UserBlock_organizationId_blockerId_idx"
  ON "UserBlock"("organizationId", "blockerId");
ALTER TABLE "UserBlock"
  ADD CONSTRAINT "UserBlock_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserBlock"
  ADD CONSTRAINT "UserBlock_blockerId_fkey"
  FOREIGN KEY ("blockerId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserBlock"
  ADD CONSTRAINT "UserBlock_blockedId_fkey"
  FOREIGN KEY ("blockedId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =====================================================
-- Source: 20260706100100_phase_31_33_34_36\migration.sql
-- =====================================================

-- Phase 31: 3D Content Plugin
-- Phase 32: Code Runner Plugin
-- Phase 33: Plugin Marketplace Governance
-- Phase 34: Popout Dual Monitor
-- Phase 36: Plugin Workspace Panels

-- =============================================================
-- Phase 31: 3D Content Plugin
-- =============================================================

CREATE TABLE "ThreeDAsset" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "format" TEXT NOT NULL,
  "sizeBytes" INTEGER NOT NULL DEFAULT 0,
  "url" TEXT NOT NULL,
  "thumbnailUrl" TEXT,
  "uploadedBy" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ThreeDAsset_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ThreeDAsset_organizationId_createdAt_idx"
  ON "ThreeDAsset"("organizationId", "createdAt");
CREATE INDEX "ThreeDAsset_organizationId_format_idx"
  ON "ThreeDAsset"("organizationId", "format");
ALTER TABLE "ThreeDAsset"
  ADD CONSTRAINT "ThreeDAsset_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ThreeDAsset"
  ADD CONSTRAINT "ThreeDAsset_uploadedBy_fkey"
  FOREIGN KEY ("uploadedBy") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ThreeDScene" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "assetId" TEXT NOT NULL,
  "scene" JSONB NOT NULL DEFAULT '{}',
  "version" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ThreeDScene_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ThreeDScene_organizationId_assetId_idx"
  ON "ThreeDScene"("organizationId", "assetId");
ALTER TABLE "ThreeDScene"
  ADD CONSTRAINT "ThreeDScene_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ThreeDScene"
  ADD CONSTRAINT "ThreeDScene_assetId_fkey"
  FOREIGN KEY ("assetId") REFERENCES "ThreeDAsset"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "ThreeDInteraction" (
  "id" TEXT NOT NULL,
  "sceneId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "trigger" TEXT NOT NULL,
  "action" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ThreeDInteraction_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ThreeDInteraction_sceneId_idx"
  ON "ThreeDInteraction"("sceneId");
ALTER TABLE "ThreeDInteraction"
  ADD CONSTRAINT "ThreeDInteraction_sceneId_fkey"
  FOREIGN KEY ("sceneId") REFERENCES "ThreeDScene"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================
-- Phase 32: Code Runner Plugin
-- =============================================================

CREATE TABLE "CodeExecution" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "language" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "output" TEXT,
  "error" TEXT,
  "durationMs" INTEGER,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMP(3),
  CONSTRAINT "CodeExecution_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "CodeExecution_organizationId_userId_idx"
  ON "CodeExecution"("organizationId", "userId");
CREATE INDEX "CodeExecution_organizationId_createdAt_idx"
  ON "CodeExecution"("organizationId", "createdAt");
ALTER TABLE "CodeExecution"
  ADD CONSTRAINT "CodeExecution_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CodeExecution"
  ADD CONSTRAINT "CodeExecution_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "CodeExecutionTestCase" (
  "id" TEXT NOT NULL,
  "executionId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "input" TEXT NOT NULL DEFAULT '',
  "expectedOutput" TEXT NOT NULL DEFAULT '',
  "actualOutput" TEXT,
  "passed" BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT "CodeExecutionTestCase_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "CodeExecutionTestCase_executionId_idx"
  ON "CodeExecutionTestCase"("executionId");
ALTER TABLE "CodeExecutionTestCase"
  ADD CONSTRAINT "CodeExecutionTestCase_executionId_fkey"
  FOREIGN KEY ("executionId") REFERENCES "CodeExecution"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "CodeSubmission" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "assignmentId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "language" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'SUBMITTED',
  "score" DOUBLE PRECISION,
  "feedback" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CodeSubmission_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "CodeSubmission_organizationId_assignmentId_idx"
  ON "CodeSubmission"("organizationId", "assignmentId");
CREATE INDEX "CodeSubmission_organizationId_userId_idx"
  ON "CodeSubmission"("organizationId", "userId");
ALTER TABLE "CodeSubmission"
  ADD CONSTRAINT "CodeSubmission_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CodeSubmission"
  ADD CONSTRAINT "CodeSubmission_assignmentId_fkey"
  FOREIGN KEY ("assignmentId") REFERENCES "Assignment"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CodeSubmission"
  ADD CONSTRAINT "CodeSubmission_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================
-- Phase 33: Plugin Marketplace Governance
-- =============================================================

CREATE TABLE "PluginListing" (
  "id" TEXT NOT NULL,
  "pluginId" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "longDescription" TEXT,
  "categories" JSONB NOT NULL DEFAULT '[]',
  "screenshots" JSONB NOT NULL DEFAULT '[]',
  "pricing" JSONB NOT NULL DEFAULT '{}',
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "submittedAt" TIMESTAMP(3),
  "publishedAt" TIMESTAMP(3),
  "reviewedBy" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PluginListing_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PluginListing_pluginId_organizationId_key"
  ON "PluginListing"("pluginId", "organizationId");
CREATE INDEX "PluginListing_organizationId_status_idx"
  ON "PluginListing"("organizationId", "status");
ALTER TABLE "PluginListing"
  ADD CONSTRAINT "PluginListing_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PluginListing"
  ADD CONSTRAINT "PluginListing_reviewedBy_fkey"
  FOREIGN KEY ("reviewedBy") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "PluginReview" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "listingId" TEXT NOT NULL,
  "reviewerId" TEXT NOT NULL,
  "rating" INTEGER NOT NULL,
  "comment" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PluginReview_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "PluginReview_organizationId_listingId_idx"
  ON "PluginReview"("organizationId", "listingId");
CREATE INDEX "PluginReview_organizationId_status_idx"
  ON "PluginReview"("organizationId", "status");
ALTER TABLE "PluginReview"
  ADD CONSTRAINT "PluginReview_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PluginReview"
  ADD CONSTRAINT "PluginReview_listingId_fkey"
  FOREIGN KEY ("listingId") REFERENCES "PluginListing"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PluginReview"
  ADD CONSTRAINT "PluginReview_reviewerId_fkey"
  FOREIGN KEY ("reviewerId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "PluginInstallation" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "listingId" TEXT NOT NULL,
  "installedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "config" JSONB NOT NULL DEFAULT '{}',
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT "PluginInstallation_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PluginInstallation_organizationId_listingId_key"
  ON "PluginInstallation"("organizationId", "listingId");
CREATE INDEX "PluginInstallation_organizationId_status_idx"
  ON "PluginInstallation"("organizationId", "status");
ALTER TABLE "PluginInstallation"
  ADD CONSTRAINT "PluginInstallation_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PluginInstallation"
  ADD CONSTRAINT "PluginInstallation_listingId_fkey"
  FOREIGN KEY ("listingId") REFERENCES "PluginListing"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "PluginPolicy" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "maxInstalls" INTEGER NOT NULL DEFAULT 50,
  "allowedCategories" JSONB NOT NULL DEFAULT '[]',
  "requireApproval" BOOLEAN NOT NULL DEFAULT false,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PluginPolicy_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PluginPolicy_organizationId_key"
  ON "PluginPolicy"("organizationId");
ALTER TABLE "PluginPolicy"
  ADD CONSTRAINT "PluginPolicy_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================
-- Phase 34: Popout Dual Monitor
-- =============================================================

CREATE TABLE "PopoutSession" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "lessonId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PopoutSession_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PopoutSession_token_key" ON "PopoutSession"("token");
CREATE INDEX "PopoutSession_organizationId_userId_idx"
  ON "PopoutSession"("organizationId", "userId");
CREATE INDEX "PopoutSession_expiresAt_idx" ON "PopoutSession"("expiresAt");
ALTER TABLE "PopoutSession"
  ADD CONSTRAINT "PopoutSession_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PopoutSession"
  ADD CONSTRAINT "PopoutSession_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================
-- Phase 36: Plugin Workspace Panels
-- =============================================================

CREATE TABLE "PluginPanel" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "pluginId" TEXT NOT NULL,
  "panelKey" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "defaultSize" TEXT NOT NULL DEFAULT 'md',
  "defaultPosition" TEXT NOT NULL DEFAULT 'right',
  "allowedRoutes" JSONB NOT NULL DEFAULT '[]',
  "configSchema" JSONB NOT NULL DEFAULT '{}',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PluginPanel_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PluginPanel_organizationId_pluginId_panelKey_key"
  ON "PluginPanel"("organizationId", "pluginId", "panelKey");
CREATE INDEX "PluginPanel_organizationId_pluginId_idx"
  ON "PluginPanel"("organizationId", "pluginId");
ALTER TABLE "PluginPanel"
  ADD CONSTRAINT "PluginPanel_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "UserPanelLayout" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "layoutKey" TEXT NOT NULL,
  "panels" JSONB NOT NULL DEFAULT '[]',
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UserPanelLayout_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "UserPanelLayout_userId_layoutKey_key"
  ON "UserPanelLayout"("userId", "layoutKey");
CREATE INDEX "UserPanelLayout_organizationId_userId_idx"
  ON "UserPanelLayout"("organizationId", "userId");
ALTER TABLE "UserPanelLayout"
  ADD CONSTRAINT "UserPanelLayout_organizationId_fkey"
  FOREIGN KEY ("organizationId") REFERENCES "Organization"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserPanelLayout"
  ADD CONSTRAINT "UserPanelLayout_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

